- hosts: localhost
  vars:
    source_ssh_key: "./.ssh/id_ed25519"
    dest_ssh_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    personal_dev_folder: "{{ lookup('env', 'HOME') }}/Development/Personal"
    clearcover_dev_folder: "{{ lookup('env', 'HOME') }}/Development/Clearcover"
  pre_tasks:
    - name: Update Apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
  tasks:
    - include: tasks/ssh.yml
    - include: tasks/zsh.yml
    - include: tasks/personal-projects.yml
    - include: tasks/clearcover-projects.yml
    # - include: tasks/git-setup.yml
    # - include: tasks/core-setup.yml
    # - include: tasks/node-setup.yml
    # - include: tasks/npm-packages.yml
    # - include: tasks/zsh-setup.yml
    # - include: tasks/slack-setup.yml
    # - include: tasks/personal-projects.yml
    # - include: tasks/nvim-setup.yml
    # - include: tasks/brave.yml
    # - include: tasks/debugger.yml
    # - include: tasks/dotfiles.yml
    # - include: tasks/productivity-tools.yml
    # - include: tasks/lsp.yml
