- name: Personal Projects - Monorepo
  ansible.builtin.git:
    repo: "git@github.com:BrianVia/projects.git"
    dest: "{{ personal }}/projects"
  tags:
    - personal-projects
- name: Personal Projects - Blog
  ansible.builtin.git:
    repo: "git@github.com:BrianVia/blog.git"
    dest: "{{ personal }}/projects"
  tags:
    - personal-projects
